### ISSUE TITLE
Maintenance and forks

### ISSUE THREAD

**Issue by davidwessman** [omniauth/omniauth_openid_connect#101]
Hello!

Glad to see that there have been some updates for this gem.

When investigatint the pcke-feature (#80) I have found a few forks that seems to be active:

- https://gitlab.com/gitlab-org/gitlab-omniauth-openid-connect (https://rubygems.org/gems/gitlab-omniauth-openid-connect)
- https://github.com/netsphere-labs/omniauth-openid-connect

Would it make sense to merge ranks with anyone of them?

**Comment by davidwessman** [comment]
@Eric-Guo Please include anyone else who might be concerned.

**Comment by hhorikawa** [comment]
Good evening,

I would like to propose that I will take over the project if m0n9oose-san don't mind.

I maintain this repository:
https://github.com/netsphere-labs/omniauth-openid-connect/
This repository has already merged with the head of @m0n9oose/omniauth_openid_connect.

So then, please permit me to upload gem packages to  
https://rubygems.org/gems/omniauth_openid_connect/

Thank you!

**Comment by andrewshadura** [comment]
At the very least it would be great if the current Git snapshot could be published, as the current last version is missing OmniAuth 2 support.

**Comment by andrewshadura** [comment]
By the way, how about talking to people from [OmniAuth](https://github.com/omniauth/) and moving the project under their namespace while simultaneously moving to group maintenance?

**Comment by bufferoverflow** [comment]
just ping me as soon as you came to a common agreement, I created the omniauth org and can create a project there and add maintainers.

@stanhu mabye also interesting for you

**Comment by stanhu** [comment]
@bufferoverflow Thanks for the ping!

We've made significant improvements to this gem in https://gitlab.com/gitlab-org/gitlab-omniauth-openid-connect. I'd suggest starting with that.

See https://gitlab.com/gitlab-org/gitlab-omniauth-openid-connect/-/blob/master/CHANGELOG.md for more details.

**Comment by bufferoverflow** [comment]
What about the gem name?
Which people could/should have access to push the gem?

@m0n9oose What do you think?

**Comment by andrewshadura** [comment]
Cc @jjbohn, who I reckon still has upload rights for the original gem.

**Comment by andrewshadura** [comment]
@m0n9oose, I guess I am to blame since I turned this discussion that way :smile:

I guess the ultimate aim is to have One Good OpenID Connect strategy for OmniAuth.
Probably the best way to achieve that would be to go through all forks and merge them together, and then probably move the project under @omniauth and maybe group-maintain it: the maintainers of existing forks (@m0n9oose, @hhorikawa, @stanhu) could probably work as a team.

What do you think?

**Comment by m0n9oose** [comment]
@hhorikawa are you asking me to allow you to push your code from a completely different repository to rubygems.org using the same gem name as this repository? Sorry, but this sounds way too dangerous, considering there are a lot of projects that use this gem.

If you have any proposals like improvements/fixes - you're welcome to open a PR.

**Comment by m0n9oose** [comment]
@andrewshadura sounds great to me. Do we have anybody from @omniauth here? Is it possible to move one of the forks under your namespace?

**Comment by andrewshadura** [comment]
I understand @bufferoverflow is.

**Comment by m0n9oose** [comment]
@andrewshadura ah, yeah, sorry I missed that. Great.

@bufferoverflow can we just move existing repository under your namespace?

**Comment by bufferoverflow** [comment]
I suggest the following:
- move this repo here to the omniauth group as it is somehow the best maintained and visible fork(I contributed to as well), I can add you @m0n9oose as owner there
- adding @m0n9oose @hhorikawa @stanhu there as maintainers
- @m0n9oose provides push rights for @hhorikawa and @stanhu 
- all are gonna use the PR workflow, no self-merge
- bring in the changes from the gitlab folks in soon to release an updated version containing those changes via the extisting gem name
- joint development in the way open source should work

WDYT?
-

**Comment by bufferoverflow** [comment]
I made @m0n9oose an owner to start the transfer, also added https://github.com/orgs/omniauth/teams/omniauth-oidc with the maintainer crew ( @m0n9oose @hhorikawa @stanhu ).

**Comment by m0n9oose** [comment]
@bufferoverflow transfer is completed. omniauth-oidc team has been added as maintainer

**Comment by m0n9oose** [comment]
@stanhu @hhorikawa i need your email addresses to add you as owners to rubygems

**Comment by pboling** [comment]
Welcome to the omniauth family! ❤️   I maintain the omniauth-identity gem.  Please ping me if I can be of help!

**Comment by bufferoverflow** [comment]
btw. I also made https://gitlab.com/omniauth long time ago so we can setup gitlab-ci if needed. https://github.com/omniauth/omniauth-org/issues/3

**Comment by andrewshadura** [comment]
Next idea: talk @jjbohn into uploading an empty gem depending on this one 🙂 Or the other way around.

**Comment by davidwessman** [comment]
I am so glad that my issue got this much traction! 🙂

**Comment by stanhu** [comment]
@m0n9oose `stanhu` at gmail.com. Thanks!

**Comment by hhorikawa** [comment]
> @stanhu @hhorikawa i need your email addresses to add you as owners to rubygems

Thank you!
I'll provide my restructured separated PRs to the repo at the new space.
My email is `hisashi dot horikawa at gmail dot com`.
https://rubygems.org/profiles/hhorikawa

**Comment by hhorikawa** [comment]
Done to update my README.

**Comment by m0n9oose** [comment]
@hhorikawa please enable 2FA on your rubygems account

**Comment by davidwessman** [comment]
I have opened a few PRs during the past week, it feels bad to @mention to get any attention to it - or is that the way to go?

**Comment by m0n9oose** [comment]
@davidwessman be patient. Your efforts are appreciated, and PRs will be reviewed as soon as possible. Please keep in mind that we work on this in our free time when we have it.

**Comment by stanhu** [comment]
Thanks all! I would welcome help upstreaming my changes in https://gitlab.com/gitlab-org/gitlab-omniauth-openid-connect.

In the interest of transparency, I've added a few colleagues with the `Triage` role to help with reviews:

1. @alexkalderimis
2. @dblessing

We should probably have some lightweight process for giving merge access to those who actively help with this project. I welcome ideas here.

**Comment by bufferoverflow** [comment]
@stanhu I think this makes sense as @alexkalderimis and @dblessing are working on the omniauth topics on your end. Maybe worth if they could start with first with some MRs here, so the other maintainers could build up trust. Maybe the  gitlab-ci file you already had? I've setup the ci already here: https://gitlab.com/omniauth/omniauth_openid_connect

btw. why this is important for me: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/8018 and follow-up https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/2804

**Comment by stanhu** [comment]
FYI, I filed a request with GitHub Support to disconnect this project form the original fork. That way pull requests will go directly to this project instead of the original project. I found it a bit confusing that new pull requests would default to the other project. 😄

**Comment by bufferoverflow** [comment]
@stanhu could you maybe add me as well to the [omniauth_openid_connectoidc omniauth](https://rubygems.org/gems/omniauth_openid_connect) owners? My user name there: https://rubygems.org/profiles/bufferoverflow

**Comment by bvogel** [comment]
@m0n9oose @stanhu are you still actively maintaining this gem? I saw a couple of good PRs from the last year that didn't get any attention.
