### ISSUE TITLE
Uninitialized constant json::jws::unknownalgorithm

### ISSUE THREAD

**Issue by Eimantas123** [omniauth/omniauth_openid_connect#146]
Error when can not decode token with jwks: `Uninitialized constant json::jws::unknownalgorithm`
https://github.com/omniauth/omniauth_openid_connect/blob/master/lib/omniauth/strategies/openid_connect.rb#L343
JWS does not have `UnknownAlgorithm` it is JWK.
https://www.rubydoc.info/gems/json-jwt/JSON/JWK/UnknownAlgorithm

**Comment by stanhu** [comment]
Thanks for reporting. Fixed in v0.6.1.
