### ISSUE TITLE
Migration guide from gitlab-omniauth-openid-connect to this gem?

### ISSUE THREAD

**Issue by ThisIsMissEm** [omniauth/omniauth_openid_connect#165]
Hi! It's great to see that you're continuing the maintenance of the omniauth openid connect strategy, I'm just wondering if there's any notes on migrating between the two that could be shared? Is this a drop-in replacement for gitlab-omniauth-openid-connect or would one have to make code changes?

**Comment by bufferoverflow** [comment]
yes, all changes should have been merged here, see also https://gitlab.com/gitlab-org/ruby/gems/gitlab-omniauth-openid-connect

**Comment by stanhu** [comment]
> Is this a drop-in replacement for gitlab-omniauth-openid-connect or would one have to make code changes?

Yes, I believe so. GitLab transitioned from this gem to v0.6.1 without any changes.

**Comment by stanhu** [comment]
The same goes for Mastodon: https://github.com/mastodon/mastodon/pull/23223

**Comment by ThisIsMissEm** [comment]
> The same goes for Mastodon: [mastodon/mastodon#23223](https://github.com/mastodon/mastodon/pull/23223)

Ha, something must've gone wrong in my local checkout, I'd seen the old gem in my copy of the code, hence opening this as I thought it hadn't been done 🤦🏻‍♀️😅
