### ISSUE TITLE
Clever SSO: clever-initated login with no state, redirect to /oauth/authorize with state

### ISSUE THREAD

**Issue by leehsueh** [omniauth/omniauth_openid_connect#187]
Hi, I'm using this gem to support openid SSO with Clever and would like to preserve csrf protection.

Clever-initiated login URLs (or I'm assuming any identity provider-initiated login URL) doesn't have a state, since it's our app that generates the value and sends it to the identity provider. That means that using this URL will result in a csrf_detected error, invalid state. Per their docs: https://dev.clever.com/docs/il-design#protecting-clever-initiated-logins, they suggest that we redirect back to the identity provider with a state that is generated to re-authorize.

Is this a flow that is supported by the gem? If not, what would be a good way to achieve something like this?

Thanks for any help and input.

**Comment by stanhu** [comment]
You might want to try setting the `send_state` parameter to `false`: https://github.com/omniauth/omniauth_openid_connect?tab=readme-ov-file#options-overview

**Comment by leehsueh** [comment]
Yeah I did play with that and it works, but it also means it's vulnerable to CSRF.

I did come up with a solution, which was to use the authentication failure route to inspect whether the provider is Clever, and redirect to the service provider URL which will re-initiate authentication with a state.
